# f = open("hello.py","w")
# n=f.write("'How are you'\n")
# print("写%d个字符"%n)
# n=f.write("'How are you'\n")
# print("写%d个字符"%n)
# f.close()
#
# f = open("hello.py","w")
# n=f.write("'How are you'\n")
# print("写%d个字符"%n)
# f.close()

# f = open("hello.py","wb")
# n=f.write(b"'How are you'\n")
# print("写%d个字符"%n)
# n=f.write(b"'How are you'\n")
# print("写%d个字符"%n)
# f.close()
#
# f = open("hello.py","wb")
# n=f.write(b"'How are you'\n")
# print("写%d个字符"%n)
# f.close()

# f = open("hello.py","a")
# n=f.write("'How are you'\n")
# print("写%d个字符"%n)
# n=f.write("'How are you'\n")
# print("写%d个字符"%n)
# f.close()
#
# f = open("hello.py","a")
# n=f.write("'How are you'\n")
# print("写%d个字符"%n)
# f.close()

f = open("hello.py","w")
n=f.writelines(['How\n','are\n','you\n'])
f.close()