content="我是京师监狱狱长金海."
print(content[0])
print(content[-1])
print(content[len(content)//2])
print(content[0:3])
print(content[-3:])
print("金海" in content)
print("京师监狱" not in content)
print(content[2:-2])
print(content[-4:1:-1])
print(content[::3])
print(content[::-1])