commodity_name = input("请输入商品名称:")
price = float(input("请输入金额:"))
comment = int(input("请输入条数:"))
store = input("请输入店铺名称:")
print(commodity_name)
print("¥"+str(price))
print(str(comment)+"条评论")
print(store)
